### PR TITLE
[web-animations-1] Add dictionary default values

### PR DESCRIPTION
**Pull request by saschanaz**
Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)

### CODE REVIEW

**Comment by saschanaz** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by birtles** [comment]
Oh, actually this needs a little more work. e.g. the [`KeyframeEffect` constructor](https://drafts.csswg.org/web-animations-1/#dom-keyframeeffect-keyframeeffect) has three lines:

* If options is a KeyframeEffectOptions object ...
* If options is a double ...
* Otherwise (options is undefined) ...

But the last option is no longer necessary.

I think that might be all.

**Comment by birtles** [comment]
(Unrelated, but something else I noticed while looking into this was that step 4 of the description of [`animate`](https://drafts.csswg.org/web-animations-1/#dom-animatable-animate) fails to account for when `options` is a `double`.)

**Comment by birtles** [comment]
I addressed the above issues in 3fafc22d659eccb596c502f6c77070e39970af6b.

**Pull request merged**
