### PR TITLE
Doing the changes in the bikeshed file. 

### PR DESCRIPTION
**Pull request by Adenilson**
Further info: https://lists.w3.org/Archives/Public/www-style/2015Oct/0127.html

### CODE REVIEW

**Comment by frivoal** [comment]
@jihyerish looks good to me, but this is your spec. Can give a look? (also, what is Hyojin's github name?)

**Comment by Adenilson** [comment]
While you are at it, would you mind to check #64 ?

**Comment by anawhj** [comment]
Looks good to me.
@frivoal Florian, Do I have the authority to merge this commit? If not, could you merge this one?

**Comment by frivoal** [comment]
@anawhj if you have a "Merge pull request" button, then you're allowed to click it. If not, I'll do it for you, but you should request access from @plinss

**Comment by anawhj** [comment]
@frivoal Thank you for the explanation. I'll request it to Peter.

**Pull request merged**
