### PR TITLE
Convert remaining Animatable lines to Animation type lines.

### PR DESCRIPTION
**Pull request by dbaron**
[css-backgrounds-4][css-box-3][css-color-hdr][css-module][css-writing-modes-3][css-writing-modes-4] Convert remaining "Animatable" lines to "Animation type" lines.

See #72.

### CODE REVIEW

**Review by svgeesus — COMMENTED** [review]
This all looks good, but what does **Animatable: n/a** mean? Is it the same as **not animatable**?

**Comment by yarusome** [comment]
This [resolution](https://github.com/w3c/csswg-drafts/issues/2751#issuecomment-402604609) _implies_ that `writing-mode` should be "not animatable", but the final resolution says differently from the proposed one.

**Comment by dbaron** [comment]
> This all looks good, but what does **Animatable: n/a** mean? Is it the same as **not animatable**?

The "n/a" values are for a propdef table that's for an alias rather than a real property.  (Perhaps aliases should be more like shorthands and say "see aliased property" or something like that.)

> This [resolution](https://github.com/w3c/csswg-drafts/issues/2751#issuecomment-402604609) _implies_ that `writing-mode` should be "not animatable", but the final resolution says differently from the proposed one.

Based on that resolution I agree that like writing-mode, direction, and unicode-bidi should all be not animatable rather than discrete.  But I don't see anything in this PR that's changing those properties.

**Review by svgeesus — APPROVED** [review]
LGTM

**Pull request merged**
