### PR TITLE
chore: Renormalize line endings

### PR DESCRIPTION
**Pull request by nschonni**
Was wondering why some files were syncing to the Bikeshed repo as "double spaced" and finally figured out it was the CRLFs that were causing it.
Ran `git add --renormalize .` to renormalize the line endings, and the .gitattributes as a backstop for further changes.

You can "review" that nothing is actually changing by looking at the diff with whitespace ignored https://github.com/w3c/csswg-drafts/pull/5934/files?diff=unified&w=1

### CODE REVIEW

**Comment by svgeesus** [comment]
Not sure this warrants making it blame useless, will see what other editors say

**Comment by nschonni** [comment]
@svgeesus good point, but I just went through the non-SVG files here and the only ones that had history beyond a previous history breaking move was https://github.com/w3c/csswg-drafts/commit/b667648046860289ec447feddbad987969929ed2#diff-c363c9a064b9de99e21077b785cb63cd43908951d8914cdcaeb4f4585fbcba58 was
- https://github.com/w3c/csswg-drafts/blob/e50d27a6c65573e313bab44d39189bbf385fe8fa/css-tables-3/Overview.bs
- https://github.com/w3c/csswg-drafts/commits/e50d27a6c65573e313bab44d39189bbf385fe8fa/geocities.css
- https://github.com/w3c/csswg-drafts/commits/e50d27a6c65573e313bab44d39189bbf385fe8fa/selectors-nonelement-1/Overview.bs

**Review by svgeesus — APPROVED** [review]
Okay, fair enough.

**Comment by tabatkins** [comment]
Fixed the merge conflict in #5940 and merged it there, so closing this one.

**Pull request closed without merging**
