### PR TITLE
[css-grid-1] Broken anchor links, fix for issue #3883

### PR DESCRIPTION
**Pull request by huijing**

### CODE REVIEW

**Comment by ewilligers** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by tabatkins** [comment]
Yeah, I'm not willing to merge a manual link, this is something wrong with Bikeshed. I'll report separately.

**Comment by tabatkins** [comment]
(Thanks for reporting the problem tho, @huijing!)

**Comment by tabatkins** [comment]
And reported as <https://github.com/tabatkins/bikeshed/issues/1466>

**Pull request closed without merging**
