### PR TITLE
[css-transitions-2][css-animations-2] Specify composite order for ::marker pseudo elements

### PR DESCRIPTION
**Pull request by birtles**

### CODE REVIEW

**Comment by birtles** [comment]
@MatsPalmgren I've specced this to match what you implemented in Gecko but I was wondering if there was any particular reason you chose that order? Is it because typically ::marker pseudo elements appear before ::before pseudo elements?

**Comment by birtles** [comment]
(I'm currently working on web-platform-tests for this which I will merge via mozilla-central.)

**Comment by MatsPalmgren** [comment]
@birtles No particular reason, since I wasn't really aware there was any particular order to pay attention to when I wrote that code.  But yes, `::marker` is considered to be before `::before` in the document order.

**Comment by birtles** [comment]
Great, thank you!

**Pull request merged**
