### PR TITLE
[css-pseudo-4] Add discussion of properties from the originating element

### PR DESCRIPTION
**Pull request by schenney-chromium**
Spec issue: https://github.com/w3c/csswg-drafts/issues/7591

Per resolution, properties not allowed on highlights but otherwise required to resolve units or modify colors are instead taken from the originating element.

### CODE REVIEW

**Comment by schenney-chromium** [comment]
Ping!

**Comment by fantasai** [comment]
Alright, question I'm not entirely clear on: what is the result of getComputedStyle() for `font-size` and `border-width` on the highlight pseudo given:

```
p { font-size: 20px; border-width: 10px; }
p::selection { font-size: 30px; border-width: 20px; }
```

?

**Comment by schenney-chromium** [comment]
> Alright, question I'm not entirely clear on: what is the result of getComputedStyle() for `font-size` and `border-width` on the highlight pseudo given:
> 
> ```
> p { font-size: 20px; border-width: 10px; }
> p::selection { font-size: 30px; border-width: 20px; }
> ```
> 
> ?

Sorry I missed this way back. In any event. getConputedStyle in Chrome reports the originating element's font size because the font size in the selection pseudo is never applied and the font size is set from the originating element always.

<html>
<style>
p { font-size: 20px; border-width: 10px;  border-style: solid; border-color: green;}
p::selection { font-size: 30px; border-width: 20px; border-style: solid; border-color: green;}
</style>
<body>
<p id="x">Hello world</p>
</body>
</html>

getComputedStyle(x, ":selection").fontSize
> 20px

The border properties are defaults, e.g. borderTopWidth > 0px.

**Comment by schenney-chromium** [comment]
I'd like to finally land this. I added the update for the custom property resolution.

**Comment by fantasai** [comment]
I think this text needs tweaking, since the language is a bit imprecise; but I think it'll be easier to tweak after merging so accepting it as-is for now.

**Pull request merged**
