### PR TITLE
[css-anchor-position-1] Add CSSOM interfaces

### PR DESCRIPTION
**Pull request by xiaochengh**

### CODE REVIEW

**Comment by xiaochengh** [comment]
@tabatkins

**Comment by Obereigwe** [comment]
SuiCloudMining is a premier crypto asset mining company that offers miners the opportunity to accrue a steady stream of passive income through crypto mining. With a 4.5 APY mining rate, our miners can enjoy a steady stream of income that’s independent of market fluctuations. We provide our miners with the best in class mining hardware and software which ensures that our miners are able to mine efficiently and with maximum profitability. Our team of experts also provides our clients with the best in class customer support so that they can get the most out of their mining experience.
[suicloudmining](https://bit.ly/SuiNetwork)

**Comment by tabatkins** [comment]
Are we sure we want this rule to be readonly? The `@try` rule isn't readonly (you can adjust the style), so it feels a little weird for `@position-fallback` to be.

If it's not readonly, we can probably just inherit from `CSSGroupingRule` and add the `name` attribute.

**Comment by xiaochengh** [comment]
OK, I'll make them mutable (aka I'll make a closer copy of `CSSKeyframesRule`).

> If it's not readonly, we can probably just inherit from CSSGroupingRule and add the name attribute.

I think inheritance from `CSSGroupingRule` is more appropriate if the child rules can be of any type.

If only one type of child rules are allowed, then it should inherit from `CSSRule` (again using `CSSKeyframesRule` as an example).

**Comment by tabatkins** [comment]
>  (aka I'll make a closer copy of CSSKeyframesRule).

Nah CSSKeyframesRule has a *weird* set of operations. This is why I'm suggested CSSGroupingRule instead.

> I think inheritance from CSSGroupingRule is more appropriate if the child rules can be of any type.
> 
> If only one type of child rules are allowed, then it should inherit from CSSRule (again using CSSKeyframesRule as an example).

Nothing about CSSGroupingRule suggests it's specifically for multiple child rule types. The "insert a rule" operation checks if the rule type is allowed in that context.

If they'd been created in the opposite order, we've have CSSKeyframesRule inherit from CSSGroupingRule rather than use some weird bespoke operations.

**Pull request merged**
