### PR TITLE
Update default-TR.css

### PR DESCRIPTION
**Pull request by panyiyi**

### CODE REVIEW

**Comment by dbaron** [comment]
Is there a reason to think the webmaster will allow publication of TR drafts without this line?

**Comment by tabatkins** [comment]
Closing this request - our stylesheet isn't up for public editting.

(Also, the base.css that's used on TR drafts now has a readable max-width.)

**Comment by FremyCompany** [comment]
It would be great though if the repo could use a stylesheet that looks more like the final one. Maybe it's just me but local builds of specs don't feature the new table of contents. Or is it because I should update bikeshed?

**Comment by tabatkins** [comment]
They... should?  I need to do some fixup to our default.css, but it imports the W3C's base.css right now, which means it should look like public ones.  They certainly do on my computer, at least.

**Pull request closed without merging**
