### PR TITLE
[css-conditional-3] Remove duplicate interface #3528

### PR DESCRIPTION
**Pull request by jugglinmike**
Tests submitted to WPT:

https://github.com/web-platform-tests/wpt/pull/17276

### CODE REVIEW

**Comment by jugglinmike** [comment]
@dbaron Would you mind taking a look?

**Comment by dbaron** [comment]
Isn't there an issue with a bit of discussion on this topic somewhere?

**Comment by jugglinmike** [comment]
The only issue of which I'm aware is pretty light on discussion https://github.com/w3c/csswg-drafts/issues/3528

**Comment by dbaron** [comment]
There's also #844 and #851, but I thought I remembered something more recent with a bit more discussion.

**Comment by jugglinmike** [comment]
Thanks, @dbaron!

**Pull request merged**
