### PR TITLE
[cssom][css-grid][css-transforms] Make 'transform-origin' and 'perspe…

### LINKED ISSUE #392: [cssom][css-transforms] Conflicting on resolved value of various properties
CSSOM has a list of properties which should have their resolved value be their used value rather than computed value. That list doesn't include `perspective-origin`. However, CSS Transforms spec says the resolved value of `perspective-origin` should be used value.

I guess one of them should be changed to match the other.

### PR DESCRIPTION
**Pull request by zcorpan**
…ctive-origin' resolved value like 'height'

Fixes #392.

### CODE REVIEW

**Comment by mrego** [comment]
Just one question, shouldn't `grid-row-gap` and `grid-column-gap` be marked too?
https://drafts.csswg.org/css-grid/#propdef-grid-column-gap

And one nit, the commit says `css-grid` but doesn't talk about grid properties. Probably it'd be nice to update the commit title and description.

**Comment by zcorpan** [comment]
> Just one question, shouldn't `grid-row-gap` and `grid-column-gap` be marked too?
https://drafts.csswg.org/css-grid/#propdef-grid-column-gap

No, the spec for those doesn't say anything about "resolved value", so they work like normal properties. (If implementations disagree, please file a new issue.)

> And one nit, the commit says `css-grid` but doesn't talk about grid properties. Probably it'd be nice to update the commit title and description.

OK, yeah.

Thanks!

**Comment by zcorpan** [comment]
Proposed commit message when merging

```
[cssom][css-grid][css-transforms] Make 'transform-origin' and 'perspective-origin' resolved value like 'height'

Also mention that 'grid-template-rows' and 'grid-template-columns'
are resolved value special case properties (no normative change).

Fixes #392.

**Comment by mrego** [comment]
>> Just one question, shouldn't grid-row-gap and grid-column-gap be marked too?
>> https://drafts.csswg.org/css-grid/#propdef-grid-column-gap

> No, the spec for those doesn't say anything about "resolved value", so they work like normal properties. (If implementations disagree, please file a new issue.)

Yes sorry for the noise, I was mixing in my mind again *computed* vs *resolved* value.

**Comment by fantasai** [comment]
Looks OK to me.

**Pull request merged**
