### PR TITLE
[css-color] Editorial: correct case for JS 'Math'

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by SebastianZ** [comment]
The [`Math` object](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-math-object) does currently not provide functions like `matrix()` or `multiply()`.

Sebastian

**Comment by zcorpan** [comment]
Oh... right... But the sample code here doesn't provide implementations of those, either?

Closing this since the suggested change is bogus.

**Comment by SebastianZ** [comment]
> Oh... right... But the sample code here doesn't provide implementations of those, either?

Correct. Those would need to be added to the sample code.

Sebastian

**Comment by svgeesus** [comment]
> But the sample code here doesn't provide implementations of those, either?

Right, that is why it uses the math library to do so :) since that library does provide them. You can look at the code easily, it is in the repo as math.js

https://github.com/w3c/csswg-drafts/tree/master/css-color

**Pull request closed without merging**
