### PR TITLE
[selectors-4] Rename :focus-ring to :focus-visible

### PR DESCRIPTION
**Pull request by alice**
Per discussion in #2036

### CODE REVIEW

**Comment by frivoal** [comment]
Looks good to me.

Just one little non essential comment:
This has been up under the focus-ring name for a while, so there could be quite a few inbound links. Just in case, it could be nice to keep a (hidden) element with the old ids (`the-focusring-pseudo`, `focus-ring-pseudo`) near the new ones, to keep the links working.

**Comment by alice** [comment]
Good idea, will fix.

**Comment by alice** [comment]
Done.

**Comment by alice** [comment]
I can't pull this but seems like it's ready to go?

**Pull request merged**
