### PR TITLE
[css-fonts-4] font-optical-sizing interacts with font-size-adjust

### PR DESCRIPTION
**Pull request by litherum**
Fixes https://github.com/w3c/csswg-drafts/issues/6190.

### CODE REVIEW

**Comment by drott** [comment]
Thanks for the quick edit, Myles. 

> Fixes #6190.

This change fixes the equivalent issue for `font-size-adjust`. It might be that you were already on it, but AFAICS we would also need an edit that clarifies this for https://drafts.csswg.org/css-fonts-5/#size-adjust-desc.

**Review by svgeesus — APPROVED** [review]
LGTM

**Comment by drott** [comment]
Oups, sorry, I was a bit quick to click the merge button. I had confused this PR with [this one](https://github.com/web-platform-tests/wpt/pull/28399) with my new tests. Should we revert and let Myles land it, after @jfkthame commented as well, or leave it in for now?

**Comment by svgeesus** [comment]
I think it is easier to leave it, we can always add more edits on top.

**Comment by svgeesus** [comment]
And yes that was super fast :)

**Pull request merged**
