### PR TITLE
[cssom-1] Follow Web IDL extended attribute changes

### PR DESCRIPTION
**Pull request by domenic**
[TreatNullAs=EmptyString] → [LegacyNullToEmptyString], per https://github.com/heycam/webidl/pull/870.

---

This should not be merged until that PR is merged, and then given a day to reach the link databases.

### CODE REVIEW

**Comment by domenic** [comment]
The Web IDL PR is merged and Shepherd seems to be updated; merge at will!

**Comment by emilio** [comment]
There seems to be some sort of ipr check that seems to be required for me to merge this... @astearns do you know what that is about?

**Comment by astearns** [comment]
That's a W3C team thing. @svgeesus or @xfq , could you make the ipr check happy?

**Comment by dbaron** [comment]
I would think that check is failing because Domenic isn't a member of the CSS WG.

**Comment by astearns** [comment]
Yeah, but that shouldn't matter because he's from a member company that is part of the group. As I understand it, it just takes someone with the right privileges to push the right button.

**Comment by xfq** [comment]
https://labs.w3.org/repo-manager/pr/id/w3c/csswg-drafts/4930 looks good to me.

@dontcallmedom Do you know why the status of IPR check is "Waiting for status to be reported"?

**Pull request merged**
