### PR TITLE
[css-grid-1][css-grid-2] Replace article to main

### PR DESCRIPTION
**Pull request by SiarheiBobryk**
Use `main` as a more suitable element in example 9.

Changes:
- Tweak the SVG image
- Use the `main` element in example 9 for _CSS Grid Layout Module Level
1_ and _CSS Grid Layout Module Level 2_

Before:
Screen Shot 2021-02-18 at 3 03 04 am

After:
Screen Shot 2021-02-18 at 3 04 16 am

### CODE REVIEW

**Comment by tabatkins** [comment]
I'm fine with this change, but it looks like you did the SVG edits in a WYSIWIG editor, which totally trashed the file with metadata; I can't merge that. The SVG should be readable and easily editable by hand, so you can swap out just the one offending word; it uses proper centered positioning, so you won't even need to adjust the position of anything.

**Comment by SiarheiBobryk** [comment]
Thanks for your feedback @tabatkins!
I've used [Inkscape](https://inkscape.org) for that. Please, could you suggest to me the best SVG editor (your opinion)?

**Comment by SiarheiBobryk** [comment]
> so you can swap out just the one offending word;

@tabatkins it's done!

**Comment by SiarheiBobryk** [comment]
@tabatkins please check

**Pull request merged**
