### PR TITLE
[css-color] Add note for relationship between color property and color glyphs

### PR DESCRIPTION
**Pull request by upsuper**
Per [discussion in the mailing list](https://lists.w3.org/Archives/Public/www-style/2016Mar/0431.html).

### CODE REVIEW

**Comment by Crissov** [comment]
Text color (and its opacity) should probably not affect PNGinOTF glyphs (`CBDT` and Apple), but should it also not affect fonts with `COLR` or `SVG ` tables? Should we solely rely on future explicit [`CPAL` control](https://drafts.csswg.org/css-fonts-4/#font-palette-control)?

#352 is somewhat related and I hope to see the issue on a WG agenda soon.

**Comment by svgeesus** [comment]
The specification for COLR and CPAL says that the color values are in sRGB.
The specification for SVG allows whatever CSS defines.

CSS4 Fonts does, as @Crissov mentions, allow palette selection, and new palettes in CSS.

**Comment by tabatkins** [comment]
I'd prefer text more like:

> Note: This property has no effect on "color glyphs", such as emoji in some fonts, which are explicitly colored by a built-in palette, unless explicitly specified otherwise by a font specification. For example, some colored fonts use a palette with the ability to refer to the "current color", such as the CPAL table in OpenType; in that case the "current color" is set by this property, identically to how the ''currentcolor'' value works.

Am I referring to things correctly here?  I'm just assuming CPAL is an OpenType table.

**Comment by litherum** [comment]
I prefer @tabatkins's comment too, because it is more descriptive.

**Comment by svgeesus** [comment]
> Am I referring to things correctly here? I'm just assuming CPAL is an OpenType table.

It is, yes. 
https://www.microsoft.com/typography/otspec/cpal.htm

**Pull request merged**
