### PR TITLE
Use bracket range notation in syntax grammar [css-values-3][css-values-4][css-backgrounds-3][css-backgrounds-4][css-multicol-1][css-multicol-2][css-flexbox-1][css-counter-styles-3]

### PR DESCRIPTION
**Pull request by AmeliaBR**
Partially addresses #355

Includes some minor fixes to the [definition of the notation](https://drafts.csswg.org/css-values-3/#numeric-ranges) @fantasai added to css-values-3.
The definition is then copied over to css-values-4 (which is what you get for just /css-values/ now).
The term "bracketed range notation" is exported for use in other specs, primarily to explain why I'm changing things.

This initial PR includes syntax edits to the specs listed as [Stable CR in the Current Work web page](https://www.w3.org/Style/CSS/current-work), and later levels of those same modules:

- CSS Backgrounds and Borders Level 3 & 4
- CSS Conditional Rules Level — no edits required
- CSS Multi-column Layout Level 1 & 2
- CSS Values and Units Level 3 & 4— edits described above
- CSS Flexible Box Layout Level 1
- CSS Cascading and Inheritance Level 3 — no edits required
- CSS Writing Modes Level 3 — no edits required, although see https://github.com/w3c/csswg-drafts/issues/2921#issuecomment-489494006
- CSS Counter Styles Level 3

See the individual commit messages for details of the changes. I've tried to match code style to each document.

Note that this currently creates some non-fatal bikeshed errors, see https://github.com/tabatkins/bikeshed/issues/1467
If that's going to take a while to get fixed, @tabatkins, it might be worth a separate PR just to merge the changes to CSS Values.

I'll be continuing to work through the remaining CR and WD specs, but that may be spread out over a few weeks, so no need to delay merging these edits waiting for an omnibus pull request. (That'll just increase the risk of merge conflicts!)

### CODE REVIEW

**Comment by frivoal** [comment]
Reviewed multicol 1&2. The edits are correct, but I wonder: you both added the bracket range notation in the grammar **and** left the equivalent restrictions in prose. Shouldn't we drop the prose now that the grammar expresses the same thing unambiguously?

**Comment by AmeliaBR** [comment]
@frivoal Because the bracket syntax is new, I thought it best to leave in the prose for clarification.

But maybe I should tidy up the prose as I go along, too?  There are a lot of different phrases used in different specs to describe these restrictions. I could switch them all to the simple "Negative values are not allowed." And maybe minimize duplication (e.g., only include that phrase once per property) when its unambiguous that it applies to multiple data types.

**Comment by frivoal** [comment]
My take would be to drop it from the prose as soon as it's added to the grammar, and write new tests to make sure it isn't ignored. But that's just me. Your approach isn't wrong either.

Can we have a third opinion?

**Comment by astearns** [comment]
I'm happy with redundancy - explaining the range in prose is another way to learn the new grammar.

**Comment by AmeliaBR** [comment]
Ok. I'll rewrite the prose to be more consistent / less verbose, but will leave some prose in place.

**Comment by AmeliaBR** [comment]
>  write new tests to make sure it isn't ignored.

For me, I'm less worried about the new grammar being ignored by implementations & more worried about it being inscrutable to authors.  I'm assuming that all these restrictions are already tested for any spec that's at stable CR, though I haven't been checking.

**Comment by AmeliaBR** [comment]
Pushed a tidy-up of the prose restrictions for these specs. Also expanded the note in CSS Values:

<blockquote>
<p class="note" role="note"><span>Note:</span> At the time of writing,
	the <a data-link-type="dfn" href="#bracketed-range-notation" id="ref-for-bracketed-range-notation①">bracketed range notation</a> is new;
	thus in most CSS specifications
	any range limitations are described only in prose.
	This does not make them any less binding.
	Common prose restrictions include
	“Negative values are not allowed” or
	“Negative values are invalid”
	to indicate a <code>[0,&infin;]</code> range.
	For an <a class="production css" data-link-type="type" href="#integer-value" id="ref-for-integer-value④">&lt;integer&gt;</a>, “Values must be greater than 0”
	is equivalent to <span class="production" id="ref-for-integer-value⑤">&lt;integer [1, ∞]&gt;</span>.</p></blockquote>

**Comment by fantasai** [comment]
Cherry-picked out (and tweaked) the css-values changes, so you'll want to drop those from the PR. Don't merge until we republish on /TR. :) Shouldn't take more than a week or two.

**Comment by AmeliaBR** [comment]
Thanks @fantasai. I've merged your changes into the PR, so they won't get messed up when this PR gets merged into master.

**Comment by fantasai** [comment]
@AmeliaBR Where you're tweaking the prose... I think using the term "invalid" is better because it more cleanly hooks into the parsing implications.

**Comment by fantasai** [comment]
@AmeliaBR Would you mind updating to use "invalid" per https://github.com/w3c/csswg-drafts/pull/3894#issuecomment-516998671 ? css-values-3 has been republished with the range notation, so after that's fixed we should be OK to merge

**Comment by svgeesus** [comment]
@AmeliaBR could you take a look at the three conflicts? It would be good to merge this PR.

**Comment by AmeliaBR** [comment]
Thanks @tabatkins (it was on my to-do, but I'm still sick & with a backlog across many projects)

**Pull request merged**
