### PR TITLE
[css-values] cap unit and copyedit

### PR DESCRIPTION
**Pull request by Crissov**
This is the trimmed down version of #848. It just adds `cap` #660, rearranges relative length units, fixes several minor mistakes and adds some line breaks to better manage possible future unit additions.

### CODE REVIEW

**Comment by tabatkins** [comment]
You've mixed together at least four different commits here, I think.  It makes it much more difficult to plumb history in the future when a commit does so many different things at once.  Please submit only the cap unit PR; the other PRs can be done separately and are likely to be merged faster.

**Comment by Crissov** [comment]
Yeah, I’m still struggling a bit with git, but shouldn’t you be able to fix that with a [squash merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits)?

**Comment by fantasai** [comment]
No, because we'd still have to separate out the changes: you've mixed up whitespace changes, a new feature, rearranging paragraphs, adding annotations, and a whole bunch of other changes into one PR. These each need to be separate commits. I can split these out manually, but in the future don't do this. I'd rather you emailed me separate patches if you can't figure out git than send a pile of tangled up commits as a PR.

**Comment by tabatkins** [comment]
I'll go ahead and close this; it can't be submitted as written, and while it could be cut down to only one change and then have a squash merge done, that can just as easily be done in a new PR.

**Pull request closed without merging**
