### PR TITLE
[css-color-4] ActiveCaption is a background.

### PR DESCRIPTION
**Pull request by emilio**
And thus shouldn't match CanvasText, but Canvas.

### CODE REVIEW

**Comment by svgeesus** [comment]
Is it? The few hits on "Active window caption" seem to suggest that it is the text (and thus, the text color) on the Windows title bar:

 - https://www.vbforums.com/showthread.php?37466-Getting-Active-Window-Caption
 - https://forum.ozgrid.com/forum/index.php?thread/47281-show-text-in-active-window-caption/

**Comment by emilio** [comment]
@svgeesus it is. The color pairs are:

 * ActiveCaption / CaptionText
 * InactiveCaption / InactiveCaptionText

**Comment by emilio** [comment]
@svgeesus the origin of these colors is win32, and the right docs are [here](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsyscolor). Quoting:

> #### COLOR_ACTIVECAPTION
>
> Active window title bar. The associated foreground color is COLOR_CAPTIONTEXT.
>
> ---
>
> #### COLOR_CAPTIONTEXT
>
> Text in caption, size box, and scroll bar arrow box. The associated background color is COLOR_ACTIVECAPTION.

**Review by svgeesus — APPROVED** [review]
Thanks for the win32 reference!

**Pull request merged**
