### PR TITLE
[cssom-view] Clarify definition of scrolling box

### LINKED ISSUE #1526: [cssom-view] "Elements and viewports have an associated scrol..."
https://drafts.csswg.org/cssom-view/#terminology

> Elements and viewports have an associated scrolling box if has a scrolling mechanism or it overflows its content area and the used value of the overflow\-x or overflow\-y property is hidden\. \[CSS3\-BOX\]
> 
> An element is potentially scrollable if all of the following conditions are true:​
> 
> The element has an associated CSS layout box\.
> The element is not the HTML body element, or it is and the root element’s used value of the overflow\-x or overflow\-y properties is not visible\.
> The element’s used value of the overflow\-x or overflow\-y properties is not visible\.
> Note:​ An element that is potentially scrollable might not have a scrolling box\. For instance, it could have overflow set to auto but not have its content overflowing its content area\.

The definition of scrolling box looks wrong. Certainly `scroll` and `auto` should also cause a scrolling box.

The definition of potentially scrollable also looks wrong w.r.t. `overflow: clip`.

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #1526.

### CODE REVIEW

**Comment by dbaron** [comment]
Is there a way to review a generated version that shows what these link to?  It's not clear to me what spec that would be in...

**Comment by zcorpan** [comment]
Generated HTML is
```html
   <p>An element or <a data-link-type="dfn" href="#viewport" id="ref-for-viewport">viewport</a> has an associated <dfn class="dfn-paneled" data-dfn-type="dfn" data-noexport="" id="scrolling-box">scrolling box</dfn> if it has a <a data-link-type="dfn" href="https://drafts.csswg.org/css-overflow-3/#scroll-container" id="ref-for-scroll-container">scroll
container</a> and <a data-link-type="dfn" href="https://drafts.csswg.org/css-overflow-3/#scrollable-overflow" id="ref-for-scrollable-overflow">scrollable overflow</a>. This box is the same as the <a data-link-type="dfn" href="https://drafts.csswg.org/css-overflow-3/#scrollport" id="ref-for-scrollport">scrollport</a>. <a data-link-type="biblio" href="#biblio-css-overflow-3">[CSS-OVERFLOW-3]</a></p>
```

**Comment by tigercosmos** [comment]
Shall we land this PR?

**Comment by dbaron** [comment]
@zcorpan - Sorry for taking so long to get back to this:

It's not clear to me why you're conditioning this on having scrollable overflow.  (And, actually, I don't think it's really defined what *having* scrollable overflow means.  I'd generally interpret that to mean that something that is included in the scrollable overflow (as the term is defined) actually overflows the padding-box.  Strictly speaking, it's defined as a set, so it's always there.)  If your intent is to condition it on whether scrollable overflow is overflowing the padding box... I'm not sure why you'd want to do that.  My instinct would be to define the concept for everything that is a scroll container.  It seems cleaner, and not doing that seems likely to be problematic for something like `overflow: scroll` without any overflow.

I'm also a little worried about element/box terminology and has/is terminology.  A [scroll container](https://drafts.csswg.org/css-overflow-3/#overflow-properties) is defined as a thing that *boxes* *are*.  This seems to say it's a thing that *elements* *have*.  I think it's probably good to use boxes.  I don't actually care about has vs. is except for being consistent.

**Comment by dbaron** [comment]
Also, if it's the same as the scrollport, why make a new term rather than using that term?

**Comment by dbaron** [comment]
Also, I guess I've looked through the uses of the term now (which I probably should have done earlier), and I suppose I see that given the uses are all related to the APIs that cause movement on scrolling, why you'd want to condition it on having scrollable overflow.  However, it seems like that usage precludes things like being able to control whether removal of content (*if* it causes a box to no longer have overflow) triggers a smooth or instant scroll.  So even given that usage, it seems better to have the term be consistently defined whether or not there's currently overflow, and handle all cases of the scrollable range changing consistently, whether or not the change in the scrollable range means there's no longer any room for movement.  And it seems like the restrictions on the range you're able to scroll to should be able to handle all the cases that not being able to scroll at all can.

(I'd also note that sometimes there's scrollable overflow that doesn't cause any ability to scroll, e.g., if it's above the scrollport.)

**Comment by zcorpan** [comment]
Replacing with scrollport seems good. I don't recall why I defined it like this.

**Pull request closed without merging**
