### PR TITLE
[css-egg-1] Add the `adafish` unit and the `performance` media query

### PR DESCRIPTION
**Pull request by Manishearth**
[css-egg-1] Add the `adafish` unit and the `performance` media query

This was first proposed by @toji in https://twitter.com/Tojiro/status/1317298532630499329 , and has rapidly gained the support of the community (me).

cc @AdaRoseCannon

r? @tabatkins  @frivoal

### CODE REVIEW

**Comment by Manishearth** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by Manishearth** [comment]
(yay, i've lost my Mozilla affiliation and can't make PRs to w3c repos that are not webxr anymore)

**Comment by frivoal** [comment]
Happy to apply editor's discretion and accept this, especially given it's well researched section about privacy and fingerprinting :)

Given that @AdaRoseCannon liked the tweet where this was proposed, I guess that she's supportive of this "feature" being specified. Wouldn't want to merge it otherwise.

I'm going to give it a few more days to give her (and the fish) an opportunity to object to possibly unwanted publicity, but lacking push back, consider this accepted.

**Comment by AdaRoseCannon** [comment]
👍  I think this is a great idea

**Comment by Manishearth** [comment]
Interesting, the spec isn't updated; it does show an error in https://drafts.csswg.org/bikeshed/css-egg-1/ but I fixed that error in this PR.

**Comment by plinss** [comment]
It should update shortly. The draft server's notion of the master branch got out of sync with the git repo.

**Pull request merged**
