### PR TITLE
Quite a few misc fixes plus rephrasing 2 paragraphs

### PR DESCRIPTION
**Pull request by Adenilson**
Further details at: https://lists.w3.org/Archives/Public/www-style/2015Oct/0163.html

### CODE REVIEW

**Comment by tabatkins** [comment]
Editting the `Overview.html` file does nothing, as it's auto-generated. You want to edit the `Overview.bs` file.

**Comment by Adenilson** [comment]
Coolio, will upload another patch ASAP.

**Comment by Adenilson** [comment]
Must be fine now.

**Comment by anawhj** [comment]
I totally agree your revisions and like it. Cool works :+1:

**Pull request merged**
