### PR TITLE
[css-ui] Add !important to input[type=hidden] portion of default stylesheet to align with HTML

### PR DESCRIPTION
**Pull request by cvrebert**
Per https://html.spec.whatwg.org/multipage/rendering.html#hidden-elements :
> ```css
> input[type=hidden i] { display none ! important; }
> ```

### CODE REVIEW

**Comment by frivoal** [comment]
The w3c's HTML5 and the whatwg's HTML seem to disagree:
http://www.w3.org/TR/html5/rendering.html#hidden-elements
https://html.spec.whatwg.org/multipage/rendering.html#hidden-elements
However, the latest W3C editor's draft concurs:
http://www.w3.org/html/wg/drafts/html/master/rendering.html#hidden-elements

So I suppose this is only a matter of being out of sync, not an actual disagreement.

**Comment by frivoal** [comment]
However, both drafts are slightly different from what's proposed here. They do
> ```css
> input[type=hidden i] { display none ! important; }
> ```

while you do

> ```css
> input[type=hidden] { display none ! important; }
> ```

**Comment by cvrebert** [comment]
Well, the Rendering section of the HTML spec uses [the case-insensitive attribute selector modifier from Selectors Level 4](https://drafts.csswg.org/selectors-4/#attribute-case) all over the place, so if you wanted to properly apply that here, you would need to modify *all* the `type=` attribute selectors in the stylesheet.
Since that wasn't directly relevant to this change and since I don't know whether using Selectors Level 4 syntax would be kosher here, I didn't modify any of the selectors.

**Comment by frivoal** [comment]
Makes sense. We can revisit with fancier selectors in level 4, but your point makes sense for level 3.

**Pull request merged**
