### PR TITLE
Add @media (prefers-ui-theme: light|dark)

### PR DESCRIPTION
**Pull request by jonathantneal**
This is a rough-draft proposal of a new media feature used to query about the color scheme being used by the operating system.

```css
/* when the system color theme is light (a light background with dark text) */
@media (color-theme: light) {
  html { background: #fff; color: #000 }
  a { color: #0000d6 }
}

/* when the system color theme is dark (a dark background with light text) */
@media (color-theme: dark) {
  html { background: #000; color: #fff }
  a { color: #00c0ff }
}
```

Applications will respond to these interface changes, and so it will be helpful if webapps can as well.

Related to #2735.

---

**JUNE 15, 2018**: I changed the proposal from `@media (interface: light|dark)` to `@media (color-theme: light|dark)` based upon @AmeliaBR’s [comment](https://github.com/w3c/csswg-drafts/issues/2735#issuecomment-395909760).

**ORIGINAL REQUEST**:

```css
/* define colors when the interface is light (dark text on a light background) */
@media (interface: light) {
  html { background: #fff; color: #000 }
  a { color: #0000d6 }
}

/* define colors when the interface is dark (light text on a dark background) */
@media (interface: dark) {
  html { background: #000; color: #fff }
  a { color: #00c0ff }
}
```

### CODE REVIEW

**Comment by jonathantneal** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by jonathantneal** [comment]
While this is a very rough draft (note the “_IN THAT BIG FANCY TYPE_” written to demonstrate things I cannot yet replicate from your specs), I would be open to modifying this PR continually into something workable with your feedback.

**Comment by dontcallmedom** [comment]
Marked as  substantive for IPR from ash-nazg.

**Comment by frivoal** [comment]
There's a clear need to address this problem, but for the reasons I explained in https://github.com/w3c/csswg-drafts/issues/2735#issuecomment-394984252, I think this pull request is premature.

This particular problem is part of a tangled nest of related questions, and we need to consider the whole thing before we dive in. Maybe we don't need to (or cannot) solve everything in one go, but we do need to consider how these various things collide and interact.

I absolutely don't want to discourage you from working on this. We've been collectively struggling for a while on how to slice the problem, and suggestions on how to cope with that would be very much welcome.

**Comment by jonathantneal** [comment]
What may I do to “make IPR commitments for this group”, so that this check in the PR will not fail?

**Comment by ewilligers** [comment]
> What may I do to “make IPR commitments for this group”, so that this check in the PR will not fail?

As a first step, perhaps [request](https://www.w3.org/accounts/request) a W3C account?

**Comment by jonathantneal** [comment]
Thanks, @ewilligers. I do have a W3C account. I tried linking that account to my GitHub account, but that failed because it says it is already linked. I can see my W3C ID in the repo manager, and I was able to “add” the CSSWG to my user, though I’m not sure what that means. I clicked around a few places, and I failed to find definitive answers.

**Comment by jonathantneal** [comment]
I’ve amended this PR today, based upon the comments in #2735.

**Comment by jonathantneal** [comment]
I’ve updated my PR based upon a consensus happening around `prefers-ui-theme`.

https://github.com/w3c/csswg-drafts/issues/2735

I have kept the `dark` and `light` variations rather than `light-on-dark` and `dark-on-light` because I softly agree with the later being “[_unnecessarily verbose_](https://github.com/w3c/csswg-drafts/issues/2735#issuecomment-420015086)”, and also because @AmeliaBR used [the shorter style](https://github.com/w3c/csswg-drafts/issues/2735#issuecomment-423625154) in a recent comment.

---

Also, I’m still flagged for “contribution issues”, and I would like to be able to "make IPR commitments". @astearns @atanassov. Would you be able to help me resolve this?

**Comment by AmeliaBR** [comment]
>  also because @AmeliaBR used the shorter style in a recent comment.

Well, I'm hardly the arbiter of all things syntactical, but I do agree with the arguments that

1. Shorter is better so long as the meaning is still clear.
2. The established terminology used in websites and operating systems is "dark theme/mode" vs "light theme/mode", not "dark-on-light mode" vs "light-on-dark mode".

**Comment by grorg** [comment]
Are you aware of #2930 ?
https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

**Comment by jonathantneal** [comment]
@grorg, no, this is the first I’ve heard of it.

**Pull request closed without merging**
