### PR TITLE
[mediaqueries-3] Mention ASCII case-insensitivity, not only case-insensitivity.

### PR DESCRIPTION
**Pull request by emilio**
Not that it's observable I think, since there are no defined media features with non-ascii characters, but...

### CODE REVIEW

**Comment by frivoal** [comment]
As that there's no effective difference between case insensitive and ASCII case insensitive in this case since there are no defined media features with non-ascii characters, I think this PR ends up just being editorial. Since updating a REC is relatively process heavy, I'm tempted to rejected it. It's not wrong, but it seems too little value for too much work.

@atanassov @astearns @svgeesus, what do you think?

**Comment by astearns** [comment]
I think it's not worth making the change to level 3

**Comment by emilio** [comment]
Sure, sounds fine, closing then. Thanks!

**Comment by dbaron** [comment]
There is a detectable difference between ASCII-case-insensitive and Unicode-case-insensitive.  For example, should "HEİGHT" (with a dot on the capital I) be a valid media feature?  The capital dotted I (İ) should lowercase to a standard ASCII lowercase i.

**Comment by emilio** [comment]
Reopening based on that.

**Comment by svgeesus** [comment]
> Since updating a REC is relatively process heavy, I'm tempted to rejected it. It's not wrong, but it seems too little value for too much work.

True, although lobbing it into an erratum is pretty easy, if we decide to accept this.

**Comment by svgeesus** [comment]
Please link `ASCII case-insensitive` as requested by @tabatkins

**Comment by emilio** [comment]
Done

**Comment by svgeesus** [comment]
Now I need to list that as an erratum ...

**Comment by frivoal** [comment]
@svgeesus Should we make a test for that, and the update the MQ3 REC? Erratum are hard to read and easy to miss. I think the answer's yes, and if the process turns out to have too much friction to make this convenient, the process should be fixed and that gives me something to do on the AB.

**Comment by frivoal** [comment]
Also, if we're going to be errataing / republishing a REC, I think we should actually have a WG resolution on the change. @astearns @atanassov ?

**Comment by emilio** [comment]
https://wpt.fyi/results/css/mediaqueries/mq-case-insensitive-001.html is already there and tests the case-insensitive / ascii-case-insensitive difference.

We landed it as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1464091, and it passes in all browsers.

So this is a bit of a no-brainer IMO, but sure, should be fine to have a resolution for this if you want :)

**Comment by frivoal** [comment]
> tests [...] passes in all browsers.
Great.

> So this is a bit of a no-brainer IMO, but sure, should be fine to have a resolution for this if you want :)

Sure, I have no disagreement about the technical issue. But there are checks along the way to publishing things on TR, and I think leaving a clear trail of how we got there helps reduce friction.

**Comment by svgeesus** [comment]
> @svgeesus Should we make a test for that, and the update the MQ3 REC?

Yes, all errata _should_ have tests (and all errata rolled into a new edition of a spec _must_ have tests).

**Pull request merged**
