### PR TITLE
[css-values-4] Section 6.1: Removed the word "unit" to avoid confusion

### PR DESCRIPTION
**Pull request by facorread**
Non-substantive contribution for grammar

### CODE REVIEW

**Comment by tabatkins** [comment]
I'm not sure what the motivation behind this change is. The spec reads fine as-is.

(You've also made several additional changes - the very first edit deletes part of the end tag, you've removed some caniuse attributes, etc.)

**Comment by facorread** [comment]
Honestly I am an outsider to all of this. Here is a screenshot of the standard today:

image

The screenshot shows that the definitions do not have the word ' unit' inside the single quotes before section 6.1.1; the confusion I was alluding to is that it makes it seem viable to write

```css
h1 {
    font-size: 1.2em unit
}
```

Similarly, I inferred that the `caniuse` values in the diff were derived from those typos.

Please let me know if these changes are introducing more problems than they fix.

**Comment by tabatkins** [comment]
If you want to move the word "unit" out of the `dfn` element, so it won't be inside the generated quotes, that would be fine with me.

**Comment by facorread** [comment]
I am happy to move the word "unit" out of `dfn`; I am not sure if there is some sort of standard way of building these titles. In another screenshot, the definitions at Section 7 come without "units" or any other word accompanying them whatsoever:

image

**Comment by tabatkins** [comment]
Ah, fair. Might as well be consistent. Okay, well fix the markup error your very first edit introduces, and put the caniuse attribute back, and I can accept this. You can go ahead and remove the `lt` attributes as well, since they'll be matching the text content and thus are unnecessary.

**Pull request merged**
