### PR TITLE
[css-values-4] Editorial: adjust to fetch refactor

### PR DESCRIPTION
**Pull request by noamr**
See https://github.com/whatwg/fetch/pull/1413

Fetch now reports timing automatically if initiator is passed.

### CODE REVIEW

**Comment by noamr** [comment]
@tabatkins this is now final after the fetch PR has been merged. fixes the WIP patch we've merged by mistake a couple of months ago

**Comment by tabatkins** [comment]
Ooooh, very nice. Thanks so much, Noam!

**Comment by triple-underscore** [comment]
> If sheet’s origin-clean flag is set, set req’s initiator to "css". [CSSOM]

request's [initiator](https://fetch.spec.whatwg.org/#concept-request-initiator) can not take value "css".
It seems that "[initiator type](https://fetch.spec.whatwg.org/#request-initiator-type)" is the correct term.

**Comment by noamr** [comment]
> > If sheet’s origin-clean flag is set, set req’s initiator to "css". [CSSOM]
> 
> request's [initiator](https://fetch.spec.whatwg.org/#concept-request-initiator) can not take value "css". It seems that "[initiator type](https://fetch.spec.whatwg.org/#request-initiator-type)" is the correct term.

Oops, you're right. https://github.com/w3c/csswg-drafts/pull/7386. Sorry for the noise @tabatkins.

**Pull request merged**
