### PR TITLE
Tipo about lime

### PR DESCRIPTION
**Pull request by scientificware**
I suspect typos in example 4 and example 26.

[css-spec-shortname-1] Brief description which should also include the #issuenum-or-URL and/or link to relevant CSSWG minutes.

Copy the above line into the Title and replace with the relevant details. Fill in any additional details here. See https://github.com/w3c/csswg-drafts/blob/master/CONTRIBUTING.md for more info.

### CODE REVIEW

**Comment by dbaron** [comment]
I think the second of these two edits would be better left the way it is now; "a lime green" is better than "a lime".  The first edit is probably OK either way.

**Comment by scientificware** [comment]
Thanks @dbaron,
Yes you are right, but it's bit currious.
Maybe we could we consider  **a "lime" color**.

**Review by svgeesus — CHANGES_REQUESTED** [review]
First edit is good, second edit (a "lime" color) is worse and should be left as-is

**Comment by svgeesus** [comment]
> Yes you are right, but it's a bit ambiguous.

Not at all. `lime` is a named color; "a lime green" is a description of a class of colors.

image

**Comment by scientificware** [comment]
@svgeesus I assume you are talking about example 26.

I think, I understand what you mean.
I was confused because "limegreen" is also a color name.
And there are no other references on class names in the document.
The purpose of this example is just to encode the same color. So why associate a class name?
Sorry for insisting.

Regards.

**Comment by svgeesus** [comment]
Class as in "category", not class as in "the class attribute".

**Comment by svgeesus** [comment]
> I presume you are talking about example 26

[Example 26](https://drafts.csswg.org/css-color-4/#srgb-linear-swatches) is about `srgb-linear`. I assume you mean [example 11](https://drafts.csswg.org/css-color-4/#ex-hex6) which is the one affected by your first commit?

**Review by svgeesus — APPROVED** [review]

**Comment by scientificware** [comment]
@svgeesus  really sorry, I was wrong, it was example 9.
Thanks for approval.

**Pull request merged**
