### PR TITLE
[selectors-4] Fix typo

### PR DESCRIPTION
**Pull request by racse1**
I've replaced a word with more formal equivalent.

### CODE REVIEW

**Comment by frivoal** [comment]
https://www.youtube.com/watch?v=dz4Ps55Rx40&feature=youtu.be&t=65

**Comment by racse1** [comment]
@tabatkins I'm sorry, didn't know that. I thought it'd be a good idea to use either of those forms consistently.

**Comment by bradkemper** [comment]
We also have “cough”, not “coff”. “Tough”, not “tuff”. “Rough”, not “ruff”. “Enough”, not “enuff”. “Thorough”, not “thurrow”. “Borough” spelled differently than “burrow”. “Bureau”, not “byurrow”.  “Align”, not “uhlline”. And countless other words with non-phonetic confusing spellings. 

Our specs should stick to English spelling as it is, not as we wish it was.

**Comment by tabatkins** [comment]
Spelling drifts with usage. ^_^  Like I said, I'm fine with it being merged, but I'm gonna keep using it myself.

**Comment by fantasai** [comment]
@racse1 As the other co-editor, I agree with @bradkemper and appreciate the fix.

**Pull request merged**
