### PR TITLE
[css-conditional-5] Container queries use the flat tree #5984

### PR DESCRIPTION
**Pull request by lilles**
Per resolution in:

https://github.com/w3c/csswg-drafts/issues/5984#issuecomment-2112977366

### CODE REVIEW

**Review by lilles — COMMENTED** [review]
Do I change "Status" to "ED" and "Prepare for TR" to "no"?

**Review by svgeesus — APPROVED** [review]

**Comment by svgeesus** [comment]
> Do I change "Status" to "ED" and "Prepare for TR" to "no"?

Not needed to land this PR but yes, we should

**Comment by lilles** [comment]
@emilio Could you take a look and see if the new wording matches your expectations?

**Review by emilio — APPROVED** [review]
Yes, this looks good to me, thanks for working on this @lilles!

**Pull request merged**
