### PR TITLE
[css-transforms] [web-animations-1] csswg github

### PR DESCRIPTION
**Pull request by ewilligers**
Issues should be created in
https://github.com/w3c/csswg-drafts/issues
not
https://github.com/w3c/fxtf-drafts/issues

### CODE REVIEW

**Comment by birtles** [comment]
I think we need WG resolution on this. I got resolution to move the spec to csswg-drafts but not explicitly to move the spec to the CSSWG proper.

There was some discussion about this in the past:

  https://lists.w3.org/Archives/Public/www-style/2016Dec/0042.html

But I believe @fantasai might still have had some reservations about it.

**Comment by tabatkins** [comment]
Moving the spec to the csswg-drafts repo definitely means issues should be in the csswg-drafts repo. You're drawing a distinction that doesn't exist.

I'll go ahead and merge.

**Comment by dirkschulze** [comment]
@tabatkins the issues is that now the header of the spec changes. With the merge, the spec is no longer an FX spec (governed by SVG WG and CSS WG) But a pure CSS WG spec. The change should get reverted and maybe Bikeshed could allow a different repo on demand from a spec.

**Comment by dirkschulze** [comment]
Oh, this now affects 3 specifications! Thought it was limited to 1 :(

**Comment by birtles** [comment]
> @tabatkins the issues is that now the header of the spec changes. With the merge, the spec is no longer an FX spec (governed by SVG WG and CSS WG) But a pure CSS WG spec

Right, that was my concern. Last time we discussed doing that, some were not entirely on board with making that change.

**Comment by tabatkins** [comment]
Is the SVGWG still even chartered? I thought that was the point.

**Comment by dirkschulze** [comment]
@tabatkins The condemned live longer.

And yes, this change would require a WG resolution from both sides. I do not expect an approval from the SVG WG just yet. At least not on specifications that used to be part of SVG. (Web animations might be different.)

**Pull request merged**
