### PR TITLE
[css-images-4] Added <element()> to <image> data type

### LINKED ISSUE #5170: element() should be part of <image>
The [`element()` function](https://drafts.csswg.org/css-images-4/#element-notation) is meant to use elements as images, though it is currently not listed in the syntax declaration of [`<image>`](https://drafts.csswg.org/css-images-4/#image-values).

Sebastian

### PR DESCRIPTION
**Pull request by SebastianZ**
Closes #5170

### CODE REVIEW

**Comment by LeaVerou** [comment]
The edit seems fine with me, though not sure about the IPR warning. @svgeesus can I still merge this?

**Comment by svgeesus** [comment]
Hi @SebastianZ could you please [link your W3C account to your GitHub account](https://www.w3.org/users/myprofile/connectedaccounts) because our IPR bot doesn't know who you are.

**Comment by SebastianZ** [comment]
Ah, I thought connecting my account on that page would be enough and I already did that back in 2019.

GitHub account connected to W3C account

Though I additionally needed to connect the Repository Manager to my GitHub account, which I did now.

Sebastian

**Comment by SebastianZ** [comment]
Hmm, but it still fails. 😞 Any hint what is missing?

Sebastian

**Comment by SebastianZ** [comment]
Could it be that my request to join the CSSWG never got accepted? At least my profile page indicates that saying

> Application for Cascading Style Sheets (CSS) Working Group on 2019/11/22
> Status for this application new

**Comment by LeaVerou** [comment]
I suspect someone needs to revalidate, but the app is failing to load the PR for me after I login. @svgeesus, could you help?

**Comment by LeaVerou** [comment]
Oh, I just noticed you have connected your Github account since 2019, so it can't have been that. I don't know what it is then. Again, someone from W3C needs to look into this, so let's wait for @svgeesus

**Comment by SebastianZ** [comment]
After accepting my request to be an invited expert (thank you!) it looks like [the Repository Manger doesn't have any issues with the request anymore](https://labs.w3.org/repo-manager/pr/id/w3c/csswg-drafts/5171) but the checks still fail.

Is there anything left I have to do in order to make the ipr bot happy?

Sebastian

**Comment by SebastianZ** [comment]
Thank you again, @frivoal!

Sebastian

**Pull request merged**
