### PR TITLE
[web-animations-1][web-animations-2] Move mutable timelines to web-animations-2

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Closes https://github.com/w3c/csswg-drafts/issues/4299

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I dont *think* anything else needs updated, but I was surprised at how small this change was.

**Comment by stephenmcgruer** [comment]
> I think section 4.4.1. Setting the timeline of an animation should be moved to level 2, right

@birtles 

I'm undecided about this. It is still used in the `Animation (effect, timeline)` constructor. That said, the timeline can't change so the steps there are probably irrelevant (have not confirmed yet). I'll need to convince myself that `setting the timeline of an animation` can't change anything during the `Animation` constructor, will look at that today :)

(Can't get github to actually show me the comment in the file, I think because it must have been made outside of the diff range? Not sure; clicking 'View changes' on your comment shows me nothing at all...)

**Comment by birtles** [comment]
> (Can't get github to actually show me the comment in the file, I think because it must have been made outside of the diff range? Not sure; clicking 'View changes' on your comment shows me nothing at all...)

I think I probably made it as a review comment as opposed to an inline comment.

> I'm undecided about this. It is still used in the `Animation (effect, timeline)` constructor. That said, the timeline can't change so the steps there are probably irrelevant (have not confirmed yet). I'll need to convince myself that `setting the timeline of an animation` can't change anything during the `Animation` constructor, will look at that today :)

I was just going off where bikeshed said that procedure was linked-to from. I didn't actually check the constructor itself so if it is used there, then we should probably leave it in level 1.

**Comment by stephenmcgruer** [comment]
Ack. I switched to a partial interface for `Animation`, I think otherwise this is good to go.

**Comment by birtles** [comment]
Thanks. I suspect we can simplify the set the timeline procedure if it is only used by the `Animation` constructor but perhaps we can do that later.

**Comment by stephenmcgruer** [comment]
Hrm, seems like neither https://drafts.csswg.org/web-animations-2/ nor the level 1 version have been updated automatically after this merge. Do we know what process usually generates them and how to check on it? @birtles @graouts

**Comment by birtles** [comment]
Sometimes the spec generation process gets blocked. I normally ping @tabatkins when that happens.

**Comment by birtles** [comment]
It appears to have run now.

**Pull request merged**
