### PR TITLE
Adding a description to address the case of a Grooved black border

### PR DESCRIPTION
**Pull request by Adenilson**
Adding a description to address the case of a Grooved black border making explicit what is the expected behavior of a UA.

For whole discussion, please see:
https://lists.w3.org/Archives/Public/www-style/2015Sep/0106.html

### CODE REVIEW

**Comment by tabatkins** [comment]
As stated in IRC by @SimonSapin, explicitly calling out "black" isn't correct here.  Near-black colors like `#000001` have the same problems, and so do colors near white.  

What we want to do is check if the difference between the "lighter" and "darker" color is sufficiently large; when the start color is near the min/max of lightness, it's not, so we'll have to shift the colors a bit.

**Comment by tabatkins** [comment]
Let's pretend for a moment that the general algorithm is "represented as HSL, the two colors are the base color, but with lightness +- 10%". (That is, 10 added/subtracted from the lightness, not multiplied by 1.1/.9.)

Then the spec text we want is something like:

> Let *base color* be the used value of 'border-color' as an HSL color.  If base color's lightness is between 10% and 90%, then *light color* and *dark color* are colors with the same hue and saturation as base color, but lightness 10% higher or lower, respectively, than base color.
> 
> Otherwise, if base color's lightness is less than 10%, dark color is black, and light color is a color with the same hue and saturation as base color, but lightness set to 20%.
> 
> Otherwise, if base color's lightness is greater than 90%, light color is white, and dark color is a color with the same hue and saturation as base color, but lightness set to 80%.

Tweak the numbers as appropriate for whatever the real light/dark adjuster is.

**Comment by SimonSapin** [comment]
:+1:

**Comment by Adenilson** [comment]
Sounds good!

**Comment by fantasai** [comment]
Closing this request without merging, since a) it's not editing the correct file and b) the statement being added is unambiguously implied by the previous statement anyway. If we want to add an algorithm, that gets filed against Level 4...

**Pull request closed without merging**
