### PR TITLE
[mediaqueries-4] Add note about min-/max- shortcoming vs proper range context

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/csswg-drafts/issues/984

### CODE REVIEW

**Comment by tabatkins** [comment]
:+1: to the note (tho given its length, I might reformat it into a `<details>`), but please remove the extra `<div class=note>` you've added; it's extraneous, as a paragraph starting with "Note: " is automatically picked up by Bikeshed and formatted accordingly already.

**Comment by patrickhlauke** [comment]
> it's extraneous, as a paragraph starting with "Note: " is automatically picked up by Bikeshed

oops, wasn't aware of that. just force-pushed an updated version of this PR. see what you think (wrapped the whole "For instance..." part into a `<div class="example">` which perhaps makes more sense now...

**Comment by tabatkins** [comment]
Ooh, much better. Thanks!

**Comment by phistuck** [comment]
Is this supposed to work on any browser at the moment?
`data:text/html,<!doctype html><style>@media (width < 320px) { html {background: black} }</style>`
Does not show black on my desktop Chrome or Firefox.

**Comment by patrickhlauke** [comment]
@phistuck this isn't really the best place to ask about current browser support, but: currently, I believe range context is not supported by any (?) browsers. (additionally, once they support it, it would only be browsers/windows with a viewport smaller than 320px that show black, so on desktop this would only happen if you made the window small and/or zoomed in)

**Comment by phistuck** [comment]
@patrickhlauke -
1. You are correct, I apologize - I got here from a Twitter suggestion for solving that problem, so I let myself go a bit because I thought it was a relevant suggestion and perhaps not a futuristic feature. ;)
2. It was a mistake, I meant `>` (I tried that as well).

Thank you!

**Pull request merged**
